bbs/urls.py
from django.urls import path
from . import views

app_name = "bbs"
urlpatterns = [
    path("", views.index, name="index"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("edit/<int:pk>/", views.edit, name="edit"),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("bbs.urls")),
]

bbs/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    
    name = models.CharField(verbose_name="カテゴリ名", max_length=20)

    def __str__(self):
        return self.name


class Topic(models.Model):

    category = models.ForeignKey(Category, verbose_name="カテゴリ", on_delete=models.CASCADE)

    name = models.CharField(verbose_name="名前", max_length=100)
    comment = models.CharField(verbose_name="コメント", max_length=2000)
    dt = models.DateTimeField(verbose_name="投稿日時", default=timezone.now)

    def __str__(self):
        return self.comment

bbs/forms.py
from django import forms
from .models import Topic

class TopicForm(forms.ModelForm):

    class Meta:
        model  = Topic
        fields = [ "category", "name", "comment" ]
        # fields はタプル型（書き換え不可能なリスト型）でもOK
        # fields = ( "comment" )

bbs/views.py
from django.shortcuts import render, redirect
from django.views import View

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Topic, Category
from .forms import TopicForm

class IndexView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        
        context = {}
        context["topics"] = Topic.objects.order_by("-dt")
        context["categories"] = Category.objects.all()

        # renderはレンダリングした結果をレスポンスオブジェクトとして返す。
        return render(request, "bbs/index.html", context)
    
    def post(self, request, *args, **kwargs):
        """
        posted = Topic( comment = request.POST["comment"] )
        posted.save()
        """
        
        form = TopicForm(request.POST)
        if not form.is_valid():
            print("バリデーションNG")
            print(form.errors)
            return redirect("bbs:index")
        
        print("バリデーションOK")
        form.save()

        return redirect("bbs:index")


index = IndexView.as_view()


class DeleteView(View):

    def post(self, request, pk, *args, **kwargs):

        topic = Topic.objects.filter(id=pk).first()

        if topic:
            print("削除")
            topic.delete()
        else:
            print("データなし")

        return redirect("bbs:index")

delete = DeleteView.as_view()


class EditView(View):

    def get(self, request, pk, *args, **kwargs):

        context                 = {}
        context["topic"]        = Topic.objects.filter(id=pk).first()
        context["categories"]   = Category.objects.all()

        return render(request, "bbs/edit.html", context)

    def post(self, request, pk, *args, **kwargs):

        topic = Topic.objects.filter(id=pk).first()
        form = TopicForm(request.POST, instance=topic)

        if form.is_valid():
            print("バリデーションOK")
            form.save()
        else:
            print("バリデーションNG")
            print(form.errors)

        return redirect("bbs:index")

edit = EditView.as_view()

templates/bbs/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bbs/css/style.css' %}">
    <title>簡易掲示板</title>
</head>
<body>
    <h1 class="bg-primary text-white">簡易掲示板</h1>

    {% block main %}
    {% endblock %}

</body>
</html>

templates/bbs/edit.html
{% extends "bbs/base.html" %}

{% block main %}

    <h2>編集画面</h2>

    <form action="" method="POST">
        {% csrf_token %}

        <select class="form-control" name="category">
            {% for category in categories %}
            <option value="{{ category.id }}" {% if category.id == topic.category.id %}selected{% endif %}>{{ category.name }}</option>
            {% endfor %}
        </select>
        <input class="form-control" type="text" name="name" placeholder="名前" value="{{ topic.name }}">
        <textarea class="form-control" name="comment" placeholder="コメント">{{ topic.comment }}</textarea>
        <input class="form-control" type="submit" values="送信">
    </form>


{% endblock %}

templates/bbs/index.html
{% extends "bbs/base.html" %}

{% block main %}
    <form method="POST">
        {% csrf_token %}
        <select class="form-control" name="category">
            <option value="" selected hidden>カテゴリ</option>
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
        <input class="form-control" type="text" name="name" placeholder="名前">
        <textarea class="form-control" name="comment" placeholder="コメント"></textarea>
        <input class="form-control" type="submit" values="送信">
    </form>

    {% for topic in topics %}
    <!-- topicsは、辞書型のリスト -->
    <div class="border">
        <div>カテゴリ:{{ topic.category.name }}</div>
        <div>{{ topic.id }}:{{ topic.dt|date:"Y-m-d H:i:s" }}</div>
        <div>{{ topic.name }}</div>
        <div>{{ topic.comment|linebreaksbr }}</div>

        <form action="{% url 'bbs:delete' topic.id %}" method="POST">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="削除">
        </form>
        <a class="btn btn-primary" href="{% url 'bbs:edit' topic.id %}">編集</a>
    </div>
    {% endfor %}

{% endblock %}